-- Important DBMS Topics & Concepts Must Study Deeply
-- ---------------------------------------------------------------------------- What is DBMS & Types of DBMS ---------------------------------------------------------------------------->
-- DBMS : A Database Management System (DBMS) is software that acts as an interface between a database and its end-users or programs. It allows users to create, read, update, and delete data while ensuring the data remains organized, secure, and easily accessible.
-- Core Working : User/Applications - DBMS Software (Handles Security, Concurrency, & Backups) - Physical Storage (Reads/Writes raw data)
-- Databases Generally Guarantees ACID properites : Atomicity : Transactions succeed completely or fail completely.
--                                                : Consistency : Data follows predefined rules.
--                                                : Isolation : Multiple users can modify data at the same time without interfering with each other.
--                                                : Durability : Once data is saved, it won't be lost even during a power crash.
-- Does All Databases guarantees ACID properties : No, While traditional relational databases view ACID as law, the reality of modern computing—fueled by massive global web traffic, real-time analytics, and Big Data—forces many databases to intentionally compromise ACID properties to achieve extreme performance and scalability.
--                                               : The Theoretical Reality : CAP Theorem - The reason all databases cannot be ACID is bound by a fundamental rule of distributed systems computer science : The CAP Theorem.
--                                                                                       - When data is distributed across multiple servers (as is required for massive global apps), you have to deal with Partition Tolerance (P)—meaning the system must keep working even if a network wire cuts connection between servers.
--                                                                         : According to the CAP theorem, if you have a network partition, you can only choose one of the following : Consistency (C): Every server returns the exact same, most recent data. (This requires locking data across servers, sacrificing speed/availability).
--                                                                                                                                                                                   : Availability (A): Every server responds immediately with data, but it might be stale or outdated data.
--                                               : Why RDBMS Chooses Consistency (CP) : Traditional relational databases were engineered in an era when storage was expensive, data was heavily structured, and business operations relied on absolute operational truth (like accounting, inventory tracking, and payroll).
--                                                                                    : The Architecture (Centralized or Strongly Coupled) : Historically, RDBMS ran on a single, massive server (vertical scaling). If you have only one server, network partitions don't exist inside the database itself, so providing full ACID safety is easy.
--                                                                                                                                         : When RDBMS evolved to use replicas (multiple servers), they implemented pessimistic locking.
--                                                                                                                                         : Reason : If a network partition splits an RDBMS cluster into two isolated halves, the database intentionally shuts down or rejects incoming writes on the disconnected nodes.
--                                                                                                                                                  : The Logic: "It is better to return an error message to the user (Sacrifice Availability) than to allow two different servers to hold conflicting financial balances or duplicate inventory records (Preserve Consistency)."
--                                               : Why Distributed NoSQL Chooses Availability (AP) : NoSQL databases were born in the early 2000s out of companies like Amazon, Google, and Facebook facing an entirely new problem: web-scale traffic. They needed to handle millions of simultaneous global users, where even a single second of a website being "down" or throwing an error meant millions of dollars in lost revenue.
--                                                                                                 : The Architecture : Shared-Nothing Distributed Rings - NoSQL databases are designed from day one to scale horizontally across hundreds or thousands of cheap commodity servers spread across global data centers. In a cluster of that size, hardware failures and network cuts are not a rare accident; they are an absolute mathematical certainty every single day.
--                                                                                                 : Reason : If a network cable snaps beneath the ocean, splitting a NoSQL database cluster into an American group and a European group, the system chooses to keep both sides completely operational.
--                                                                                                          : The Logic: "It is better to let a user successfully post a comment, add an item to a shopping cart, or update their profile right now (Preserve Availability) even if users on the other side of the world can't see that update for a few seconds. We will write the data locally and resolve the conflicts later once the network heals (Sacrifice Consistency)."
--                                               : The Practical Reality : BASE instead of ACID : To handle millions of users across the globe simultaneously, NoSQL databases adopted a completely different philosophy known as BASE
--                                                                                              : Basically Available : The database values keeping the system online and responding over keeping it perfectly accurate.
--                                                                                              : Soft State : The data can change over time dynamically without direct user interaction, as servers slowly update each other behind the scenes.
--                                                                                              : Eventual Consistency : The data will eventually become consistent across all servers, but it is not guaranteed to be identical right now.
--                                               : The Real World Example : The ACID Reality (Banking) : If you withdraw $100 from an ATM, your balance must update instantly everywhere. If the network drops, the database must halt the transaction entirely. It cannot be "eventually consistent."
--                                                                        : The BASE Reality (Instagram/X) : If a celebrity posts a photo, a user in London might see it 2 seconds before a user in Tokyo. The Tokyo server is temporarily "stale." The database doesn't crash or block traffic over this; it prioritizes availability and catches up a few moments later.
--                                               : The Current State of the Industry (The Convergence) : The database landscape isn't a strict binary anymore. The reality in 2026 is that the line between ACID and NoSQL has heavily blurred:
--                                                                                                     : NoSQL adding "Opt-in" ACID : Many NoSQL databases realized that developers still occasionally need ACID guarantees for specific features (like checkout carts). For instance, MongoDB added multi-document ACID transactions, allowing developers to switch on ACID safety when needed and turn it off for raw speed elsewhere.
--                                                                                                     : Polyglot Persistence : Most large companies do not use just one database. In reality, an architecture will route financial transactions through an ACID-compliant SQL database (like PostgreSQL) while routing real-time user feeds, chats, and analytics through a fast, horizontally scalable BASE database (like DynamoDB or Redis).

-- Types of DBMSs : DBMS types are primarily categorized by how they structurally organize and store data inside the system.
--                : Relational DBMS (RDBMS) : This is the most common type. Data is stored in fixed, structured tables consisting of rows and columns. Tables are linked (related) to one another using shared keys. It relies heavily on SQL (Structured Query Language).
--                                          : Best for : Applications requiring strict data accuracy, financial systems, and complex queries.
--                                          : Examples : MySQL, PostgreSQL, Oracle, Microsoft SQL Server.
--                : NoSQL (Not Only SQL) DBMS : NoSQL systems drop the strict table structure to prioritize scalability and speed. They can manage unstructured or semi-structured data effortlessly. NoSQL is split into four main sub-types based on architectural choices:
--                                            : Document Databases : Data is stored as JSON-like documents (e.g., MongoDB).
--                                            : Key-Value Stores : Data is stored as a simple dictionary pairing unique keys to values (e.g., Redis).
--                                            : Column-Oriented Databases : Data is stored in columns instead of rows, optimized for massive data analytics (e.g., Cassandra).
--                                            : Graph Databases : Data is stored as "nodes" (entities) and "edges" (relationships), perfect for social networks or fraud detection mapping (e.g., Neo4j).
--                : Hierarchical DBMS : Data is organized in a top-down, parent-child tree structure. Each parent record can have multiple child records, but a child record can only have one parent.
--                                    : Best for High-performance legacy systems. Examples : IBM’s Information Management System (IMS).
--                : Network DBMS : An evolution of the hierarchical model designed to handle more complex relationships. It structures data like a graph where a child record can have multiple parent records (many-to-many relationships).
--                               : Best for Complex structural mapping on older mainframe systems. Examples : Integrated Data Store (IDS).
--                : Object-Oriented DBMS (OODBMS) : Instead of converting data into tables, this system stores information directly as objects, exactly how they are represented in object-oriented programming languages (like Java, C++, or Python).
--                                                : Best for Engineering, 3D modeling, and applications with deeply complex data objects.
--                                                : Examples : ObjectStore, db4o.

-- ---------------------------------------------------------------------------- ACID Properties, Usage & Case Studies along with practical implementation ---------------------------------------------------------------------------->
-- ACID Properties : The word ACID is an acronym where each letter represents a strict guarantee that a database management system must uphold during a transaction (a sequence of one or more operational steps treated as a single execution unit).
--                 : Atomicity (The "All-or-Nothing" Rule) : Atomicity ensures that a transaction containing multiple database operations is treated as a single, indivisible unit of work. Either all changes are permanently saved, or none of them are.
--                                                         : The Mechanism : Databases achieve this using a Write-Ahead Log (WAL) or a transaction journal. Before any data is modified on disk, the database writes the intended changes to a sequential log file. If a crash or error occurs mid-transaction, the engine reads this log backwards to execute an Undo/Rollback operation, restoring the exact state prior to ignition.
--                 : Consistency (The "Rule-Abiding" Rule) : Consistency dictates that a transaction can only bring the database from one valid state to another valid state, maintaining all schema invariants, rules, constraints, and cascades.
--                                                         : The Mechanism: This is enforced by schema-level validation engines. If a transaction attempts to insert an invalid data type, violate a FOREIGN KEY constraint, or break a custom database trigger rule, the engine automatically triggers an exceptional fault, aborts the chain, and executes a rollback to protect structural integrity.
--                 : Isolation (The "Invisible-Neighbor" Rule) : Isolation guarantees that concurrently executing transactions do not interfere with each other. The database must make concurrently running operations appear as if they are executing sequentially (one after the other).
--                                                             : The Mechanism : Isolation levels are handled via concurrency control algorithms. The absolute gold standard for strict isolation is Two-Phase Locking (2PL), which locks records during read/write cycles to prevent overlapping modifications. Modern highly performant engines typically employ Multi-Version Concurrency Control (MVCC), which creates localized timestamped snapshots of rows so reads never block writes and writes never block reads.
--                 : Durability (The "Persistence" Rule) : Durability guarantees that once a transaction commits, its modifications are permanently recorded in non-volatile storage (the hard drive or SSD) and will not be lost even if the underlying server crashes or loses power immediately afterward.
--                                                       : The Mechanism : This relies on hardware-level disk synchronization. When a database issues a COMMIT command, it calls an operating system operation called fsync(). This forces the kernel to flush the temporary volatile system memory caches straight into the physical disk blocks before returning a success signal back to the client application code.

-- Concurrency Anomalies & Isolation Levels : To understand Isolation in practice, you must understand what happens when you turn isolation settings down to gain raw speed. There are 4 standardized isolation levels defined by ANSI/ISO SQL, each defending against specific structural anomalies.
--                                          : The Concurrency Anomalies : Dirty Read : Transaction A modifies a row but hasn't committed yet. Transaction B reads that modified row. Transaction A aborts and rolls back. Transaction B is now processing invalid "phantom" data that technically never existed.
--                                                                      : Non-Repeatable Read : Transaction A reads a row. Transaction B updates that same row and commits. Transaction A reads the exact same row again but sees completely different column values.
--                                                                      : Phantom Read : Transaction A runs a query looking for all users with an age > 21 and gets 10 rows. Transaction B inserts a brand-new user aged 25 and commits. Transaction A runs the exact same query again and suddenly finds 11 rows.
--                                          : Why a "Non-Repeatable Read" is a Problem : Imagine an automated banking system generating an automated monthly report.
--                                                                                     : The Reporting Script reads your account balance. It sees $1,000.
--                                                                                     : Right at that exact millisecond, you tap your debit card at a grocery store. A separate transaction updates your balance to $950 and commits it.
--                                                                                     : The Reporting Script, as part of its next step in the same transaction, reads your balance again to double-check it for a calculation. Suddenly, it reads $950.
--                                                                                     : The Consequence : Inside the exact same report run, the system has read two completely different balances for you. This causes mathematical errors, mismatching ledger totals, and software crashes because the data changed mid-stream.
--                                          : Why a "Phantom Read" is a Problem : Imagine an HR manager running a bonus distribution program for top-performing employees.
--                                                                              : The HR Script queries the database: "Find all employees with a performance score > 90 so we can transfer a $5,000 bonus to them." The database finds 10 employees.
--                                                                              : While the script is preparing the wire transfers, an administrator in another window inserts a 11th employee who also has a score > 90 and hits save.
--                                                                              : The HR Script executes the final transfer command using the same criteria. Suddenly, 11 bonuses are paid out, but the system's audit log only recorded the original 10 entries it pulled in step 1.
--                                                                              : The Consequence : New data records ("phantoms") materialized out of nowhere in the middle of a single transaction, causing the system to pay out unrecorded money.
--                                          : Why a "Dirty Read" is a Problem : Imagine you are booking a flight. There is 1 seat left on the plane.
--                                                                            : User A clicks "Book Ticket." The database temporarily updates the seat count from 1 to 0 while processing User A's credit card.
--                                                                            : User B refreshes the page. Because the database allows Dirty Reads, User B's transaction reads that uncommitted 0 and displays: "Sorry, this flight is fully booked." User B leaves the website.
--                                                                            : User A's credit card is declined. User A's transaction crashes, aborts, and rolls back the seat count from 0 back to 1.
--                                                                            : The Consequence : The seat is actually available, but you just lost User B's business because they read "dirty," uncommitted data that technically vanished a second later.
--                                          : The Standard ANSI/ISO Isolation Level Matrix : Read Uncommitted : It is an obsolete baseline state. It solves nothing and is treated as a safety-off "Wild West" switch. Major engines like PostgreSQL secretly promote it to Read Committed automatically to prevent data corruption.
--                                                                                         : Read Committed : Read Committed creates an architectural rule: A transaction can only read data that has been officially saved (COMMIT) to disk. It achieves this using a technique called Statement-Level Multi-Version Concurrency Control (MVCC).
--                                                                                                          : Step-by-Step Breakdown : Isolation Bubble : When Transaction 1 ($T_1$) modifies a row (changing inventory from 10 to 9), that change is kept in a temporary, uncommitted state.
--                                                                                                                                   : The Shield : When Transaction 2 ($T_2$) runs a search query, the database takes a quick snapshot of the last officially saved state.
--                                                                                                                                   : The Block : The database reads from this safe snapshot and returns 10 to $T_2$, completely ignoring $T_1$'s uncommitted ghost data.
--                                                                                         : Repeatable Read : Repeatable Read ensures that once a transaction reads a row, the values in that row remain completely frozen for the entire lifespan of that transaction. It achieves this using Transaction-Level Multi-Version Concurrency Control (MVCC).
--                                                                                                           : Step-by-Step Breakdown : The Bubble Creation : The exact millisecond Transaction 1 ($T_1$) begins, the database takes a single, timestamped data snapshot. $T_1$ reads the inventory value as 10.
--                                                                                                                                    : The External Change : Transaction 2 (T2) modifies that same inventory row, reducing the count to 5, and officially commits it to the disk.
--                                                                                                                                    : The Shield : When T1 re-runs the exact same query later, the database completely ignores the disk update and reads directly from T1's private, original snapshot bubble, safely returning 10.
--                                                                                         : Serializable : Serializable completely removes snapshots for range criteria and forces competing transactions into a strict, single-file line. It achieves this using Pessimistic Range/Predicate Locking or advanced conflict dependency tracking.
--                                                                                                        : Step-by-Step Breakdown : Territory Lock : The moment Transaction 1 (T1) queries a range (e.g., searching for items priced > $500), the database places a lock over that entire data territory.
--                                                                                                                                 : The Block : Transaction 2 (T2) tries to insert a brand-new row (a $600 headset) that falls directly into that locked price range.
--                                                                                                                                 : The Shield : Instead of letting the write slip through, the database freezes T2, forcing it to wait in a queue until $T_1$ completely finishes and commits its work.


-- 2. Basic Hands On Experience on some Major Polpular DBMS - MySQL, PostgreSQL, MongoDB, Redis
-- 4. What is 3-Schema Architecture?
-- 5. What is Data Independence?
-- 6. Conceptual & Practical Understanding & Hands On with different Database Connections with Different Architectures & Tech Stack
-- 7. Understanding & Usage of different Keys & Constraints : Primary Key, Foreign Key, Candidate  Key, Super Key, Composite Key & Surrogate Key
-- 8. Normalisation, concept, & practical implementation knowledge and understanding : 1NF, 2NF, 3NF, 4NF, BCNF & De Normalisation
-- 9. Transactions in Databases
-- 10. Handling Concurrency in Databases
-- 11. Understanding Dirty Read concepts and related
-- 12. Understanding Phanton Read concepts and related
-- 13. Understanding different Isolation Levels and related
-- 14. Deadlock understanding and practical knowledge and related.

-- Important SQL Topics & Concepts Must Study Deeply
-- 1. DDL, DML, DCL, TTL
-- 2. Understanding Delete, Truncate & Drop in depth
-- 3. Inner Join, Full Outer Join, Left Join, Right Join, Self Join & Self Join
-- 4. Advanced Functions & Features : Aggregate Functions and Usage
--                                  : Having & Group By
--                                  : Having vs Where
--                                  : SubQuery
--                                  : Co Related Query
--                                  : Common Table Expression & WITH keyword usage
--                                  : Important Window Functions : ROW_NUMBER(), RANK(), DENSE_RANK()

-- Optimizations & Internals
-- 1. Understanding of Indexings : Cluster & Non Cluster Indexing
-- 2. B-Tree
-- 3. Query Performance
-- 4. Index Scan
-- 5. Index Seek
-- 6. Query Tuning

-- More Advanced Topics to Conquer
-- 1. NoSQL vs. SQL (Polyglot Persistence)
-- 2. Database Scaling & Architecture : Vertical Scaling, Horizontal Scaling, Sharding & Replication
-- 3. CAP Theorem (Distributed Systems)
-- 4. Advanced Coding: Handling Edge Cases
-- 5. Views, Triggers, and Stored Procedures
